name: Output Information
on: [workflow_dispatch]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: |
          echo "${{ toJson(github) }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.event_name: ${{ github.event_name }}"
